@startuml

actor MC as "Marketing Consultant"
actor LS as "Location Scout"
actor EP as "Economics Professor"

rectangle Database

rectangle "Report Generator" {
    usecase UC1 as "Get population by country
    in order of largest to smallest."

    usecase UCa as "Print populations"

    MC - UC1
    UC1 ..> UCa : include
    UC1 - Database

    usecase UC2 as "Get population by continent
    in order of largest to smallest."
    MC - UC2
    UC2 ..> UCa : include
    UC2 - Database

    usecase UC3 as "Get population by region
    in order of largest to smallest."
    LS - UC3
    UC3 ..> UCa : include
    UC3 - Database

    usecase UC4 as "The top N populated countries in the world
    where N is provided by the user."
    EP - UC4
    UC4 ..> UCa : include
    UC4 - Database

@enduml