@startuml

actor MC as "Marketing Consultant"

rectangle Database

rectangle "Report Generator" {

    usecase UC1 as "Get population by country
    in order of largest to smallest."

    usecase UCa as "Print populations"
    usecase UCb as "Print cities"

    MC - UC1
    UC1 ..> UCa : include
    UC1 - Database

    usecase UC2 as "Get population by continent
    in order of largest to smallest."
    MC - UC2
    UC2 ..> UCa : include
    UC2 - Database

    usecase UC3 as "Get population by region
    in order of largest to smallest."
    MC - UC3
    UC3 ..> UCa : include
    UC3 - Database

    usecase UC4 as "The top N populated countries in the world
    where N is provided by the user."
    MC - UC4
    UC4 ..> UCa : include
    UC4 - Database

    usecase UC5 as "The top N populated countries in a continent.
    Where the continent and N are provided by the user."
    MC - UC5
    UC5 ..> UCa : include
    UC5 - Database

    usecase UC6 as "The top N populated countries in a region.
    Where the region and N are provided by the user."
    MC - UC6
    UC6 ..> UCa : include
    UC6 - Database

    usecase UC7 as "All the cities in the world organised
    by largest population to smallest."
    MC - UC7
    UC7 ..> UCb : include
    UC7 - Database

    usecase UC8 as "All the cities in a continent organised
    by largest population to smallest."
    MC - UC8
    UC8 ..> UCb : include
    UC8 - Database

@enduml